// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	GetRequest
	SaveRequest
	UserResponse
	User
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SaveRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *SaveRequest) Reset()                    { *m = SaveRequest{} }
func (m *SaveRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()               {}
func (*SaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SaveRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Username  string `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*SaveRequest)(nil), "pb.SaveRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterType((*User)(nil), "pb.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for UserService service

type UserServiceClient interface {
	// Sums two integers.
	GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Concatenates two strings
	SaveUser(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SaveUser(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/SaveUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	// Sums two integers.
	GetUser(context.Context, *GetRequest) (*UserResponse, error)
	// Concatenates two strings
	SaveUser(context.Context, *SaveRequest) (*UserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/SaveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SaveUser(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "SaveUser",
			Handler:    _UserService_SaveUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x6d, 0xed, 0x6a, 0x77, 0x2a, 0x2a, 0xc1, 0x43, 0x59, 0xf6, 0x20, 0x39, 0x09, 0x6a,
	0x85, 0xf5, 0x21, 0xbc, 0x79, 0xe8, 0xe2, 0x03, 0xa4, 0x3a, 0x42, 0x60, 0xdb, 0xc6, 0x24, 0xed,
	0x03, 0xf8, 0xe4, 0x66, 0xa6, 0xff, 0x44, 0x84, 0xbd, 0xe5, 0x9b, 0x6f, 0x7e, 0xcc, 0x97, 0x0f,
	0xa0, 0x73, 0x68, 0x0b, 0x63, 0x5b, 0xdf, 0x8a, 0xd8, 0x54, 0x72, 0x0b, 0xf0, 0x82, 0xbe, 0xc4,
	0xaf, 0x0e, 0x9d, 0x17, 0x97, 0x10, 0xeb, 0x8f, 0x3c, 0xba, 0x8d, 0xee, 0xd6, 0x65, 0x78, 0xc9,
	0x7b, 0xc8, 0xf6, 0xaa, 0xc7, 0xc9, 0xde, 0x42, 0x42, 0x38, 0x2f, 0x64, 0xbb, 0xb4, 0x30, 0x55,
	0xf1, 0x16, 0x74, 0xc9, 0x53, 0xf9, 0x00, 0x17, 0xac, 0xd0, 0x99, 0xb6, 0x71, 0x78, 0x64, 0xfb,
	0x3b, 0x82, 0x84, 0xe4, 0xdf, 0x9b, 0x01, 0x5b, 0x7f, 0x6a, 0xeb, 0xfc, 0xab, 0xaa, 0x31, 0x8f,
	0x79, 0xbc, 0x0c, 0xc4, 0x06, 0xd2, 0x83, 0x1a, 0xcd, 0x53, 0x36, 0x67, 0x2d, 0x6e, 0x60, 0x85,
	0xb5, 0xd2, 0x87, 0x3c, 0x61, 0x63, 0x10, 0x44, 0xd0, 0xc1, 0x86, 0x88, 0xd5, 0x40, 0x4c, 0x7a,
	0x57, 0x43, 0x46, 0x19, 0xf6, 0x68, 0x7b, 0xfd, 0x8e, 0xe2, 0x11, 0xce, 0x43, 0x19, 0x43, 0x2a,
	0x8a, 0xbb, 0x34, 0xb3, 0xb9, 0x9e, 0xe3, 0x8f, 0xdf, 0x93, 0x27, 0xe2, 0x09, 0x52, 0x6a, 0x87,
	0xf7, 0xaf, 0xc8, 0xff, 0xd5, 0xd5, 0x7f, 0x40, 0x75, 0xc6, 0xbd, 0x3f, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xd4, 0xff, 0x20, 0x61, 0x85, 0x01, 0x00, 0x00,
}
